### ISSUE TITLE
Improving User Experience with Updated Text Boxes, Flucht Button, Hover Effects, and Sound Effects

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project-pokemon-battler#13]
## Value Proposition

**As a player
**I want to have a better gameplay experience with enhanced user interface features and immersive sound effects
**so that I can enjoy the game even more.
​

## Description

![us6](https://user-images.githubusercontent.com/100302405/230336789-b2d7a950-1739-472b-b565-641fe6683f31.png)

The user interface of the game should be improved by adding an "escape" button that allows the player to leave the current fight and return to the previous menu/restart the fight. The text boxes should also be updated. In addition, hover effects should be added to the menu buttons to provide visual and audio feedback and improve the user experience.

Sound effects should also be added to the game to create an immersive atmosphere for the player.

## Acceptance Criteria

- [x] The user interface of the game should include a "Flucht" button that allows the player to escape the current battle and return to the previous menu.
- [x] The text boxes should be updated.
- [x] Hover effects should be added to the menu buttons to provide visual feedback and improve user experience.
- [x] Sound effects should be added to the game to create a more immersive and engaging atmosphere for the player.
      ​

## Tasks

- [x] Add a "Flucht" button to the menu, allowing the player to escape the current battle and return to the previous menu.
- [x] Add hover effects to the menu buttons to provide visual feedback and improve user experience.
- [x] Add sound effects to the game
- [x] create a useSoundEffect.js with Sound Library 
- [x] create new Animations

**Comment by actyvystom** [comment]
A very detailed and verbose one! 
Description and Acceptance Criteria are identical... please try to refactor and rephrase your description, add some wireframe to visualize your description.

**Comment by dennisbuchwald** [comment]
thank u, have revised the user story :)

**Comment by supernova-97** [comment]
Very excited to see how this will turn out!
I think the first 2 tasks are the same tho?

**Comment by dennisbuchwald** [comment]
@supernova-97 oh yes haha, c&p issue
