### ISSUE TITLE
Implementing Pokemon Selection Menu

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project-pokemon-battler#15]
## Value Proposition

**As a player
**I want to be able to select one of three Pokemon to battle with
**in order to have a unique and personalized battle experience.
​

## Description

![us7](https://user-images.githubusercontent.com/100302405/230388532-8c9b11e6-e322-4bd0-a4e8-d68840e05c2d.png)

A Pokemon selection menu should be added to the game, where the player can choose one of three available Pokemon for battle. The selected Pokemon will then fight the trainer's Pokemon. The battle screen should be updated to show the Pokemon selected by the player, its name, and its HP bar.
​

## Acceptance Criteria

- [x] A Pokemon selection menu should be added to the game.
- [x] The player should be able to select one of three available Pokemon to battle with.
- [x] The selected Pokemon should then battle against the trainer's Pokemon.
- [x] The battle screen should be updated to display the player's selected Pokemon, their name, and HP bar.
      ​

## Tasks

- [x] Create a Pokemon selection menu component.
- [x] Implement logic to allow the player to select one of three available Pokemon to battle with.
- [x] Update the battle screen to display the player's selected Pokemon, their name, and HP bar.
- [x] create an array with three pokemon with three attacks each 
- [x] Integrate the respective attacks into `useBattleLogic.js`

**Comment by alexWaligorski** [comment]
Souns good to me! I am only not sure what you mean by "create attacks fo the respective pokemon". Can you be more specific about it? Otherwise it sounds like it's own user story...where you have to write some attack logic. Here, as fas as I understood, the focus lies on displaying and choosing one of three pokemon.

**Comment by dennisbuchwald** [comment]
Thank you so much for your comment Alex! ❤️

No, the attack logic is already integrated into the game.
I want to have three attacks for each of the three payable pokemons.
That means: depending on which poekmon I choose, the displayed attacks, the name, the level and the HP should change from the values of the created array. 
Behind the array is then for the attacks a "strand" with which then in the useBattleLogic.js is worked and manipulated according to different factors. 

Does it make it so more understandable?

**Comment by alexWaligorski** [comment]
Yeah, this makes a lot of sense and sounds so, so cool! Maybe it would help to channge "create attack" to "integrate" attack logic from useBattleLogic, so reviewer will know this already existed before.

Looking forward to playing around with the feature in QA.

**Comment by dennisbuchwald** [comment]
You are 100% right, I have updated so. Look gladly again about it and thank you for your feedback!
