### ISSUE TITLE
Implementing Difficulty-Based Battle Logic

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project-pokemon-battler#19]
## Value Proposition

**As a player
**I want the battle logic to vary according to the difficulty level I have chosen
**in order to have a challenging and fair battle experience.
​

## Description

The battle logic should be updated to vary according to the difficulty level chosen by the player. The easiest difficulty level should have a simplified battle logic, while the most challenging level should have more complex and advanced battle logic. This will ensure that the battle experience is fair and balanced, regardless of the difficulty level selected.

## Acceptance Criteria

- [x] The combat logic should vary depending on the difficulty level chosen by the player.
- [x] The easiest difficulty level should be a simplified combat.
- [x] The most difficult difficulty level should be an advanced combat.

## Tasks

- [x] Implement logic to vary the combat logic depending on the difficulty level chosen by the player.
- [x] Revise useBattleLogic.js.
- [x] Attack strength should be influenced by the level of the respective pokemon, this logic must be integrated as well.
- [x] Each opponent pokemon should have different attack strength, this value must be added in the array of pokemons and used in BattleLogic.

**Comment by manukao** [comment]
Clear and concise, lgtm 👍 very eager to see and play the final version!

**Comment by dennisbuchwald** [comment]
@manukao oh yes haha, you're right. changed! thank you! ❤️
