### ISSUE TITLE
Displaying the Battle Screen

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project-pokemon-battler#2]
## Value Proposition

- As a player
- I want to see the battle screen
- in order to prepare for the upcoming battle.

## Description

![us1](https://user-images.githubusercontent.com/100302405/227489144-b86ec615-b5ff-4d2e-83d4-6176008aaa0d.png)

## Acceptance criteria

- [x] The battle screen should display the player's and opponent's 
        Pokemon, their names, and their HP bars.

## Tasks

- [x] Create the battle screen component.
- [x] Implement logic to display the Pokemon, their names, and their 
        HP bars.
- [x] Write tests to ensure the functionality is working as intended.
- [x] Create a  folder with ressources.

**Comment by alexWaligorski** [comment]
looks great! i can not really grasp whether this is maybe a little bit to complex for the start. my only suggestion would be to add to tasks: create db.js or folder with ressources (images, pokemon data etc.)

**Comment by PReichetanz** [comment]
Agreed with @alexWaligorski.

I have one thing though: The question "Was willst Du tun?" supposes that the user can do something, but that's not true. This is why I would argue to remove this part and move it to the next story as soon as you implement an action started by the user.

**Comment by LuYujin9** [comment]
looks really cool

**Comment by abieber1408** [comment]
Looks Nice!!
Split and simplify in different stories. 
You only want to see the screen?

**Comment by actyvystom** [comment]
A nice one! 🚀
