### ISSUE TITLE
Implementing Healing Functionality with Potion Item in Battle

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project-pokemon-battler#20]
## Value Proposition

As a player
I want to be able to open my bag and use a potion during battle to heal my Pokemon
to heal to increase my chances of victory and make the battle experience more dynamic
​

## Description

![us9](https://user-images.githubusercontent.com/100302405/231750844-bd6f1a4b-01fa-41eb-a57d-62377c87047e.png)

A "Bag" button should be added to the battle screen that allows the player to open their bag and select a potion to use. The potion selected should heal the player's Pokemon by a certain amount of HP. This will give the player a strategic advantage in battle and make the experience more dynamic.
​

## Acceptance Criteria

- [x] A "Bag" button should be displayed
- [x] The player should be able to open their bag and select a potion to use.
- [x] The selected potion should heal the player's Pokemon by a certain amount of health.
      ​

## Tasks

- [x] Create a "Bag" button component for the battle screen.
- [x] Implement logic to allow the player to open their Bag and select a Potion item to use.
- [x] Implement logic to heal the player's Pokemon by a fixed amount of HP when a Potion is used.

**Comment by manukao** [comment]
also very nice idea, lgtm - though there seems to be a typo/ text missing, see first acceptance criteria. "... should be displayed"

**Comment by dennisbuchwald** [comment]
@manukao @manukao oh yes haha, you're right. changed! thank you! ❤️
