### ISSUE TITLE
Finalizing Mobile-First Design and Optimizing Objects for iPhone SE

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project-pokemon-battler#23]
## Value Proposition

As a player
I want the mobile-first design to be finalized and all objects to be optimized for the iPhone SE
in order to have an optimal user experience on these devices.
​
## Description

<img width="499" alt="Pokemon Battler" src="https://user-images.githubusercontent.com/100302405/232449546-e5095c2c-f67a-4fc4-926b-bd1204290bb7.png">

The mobile-first design should be finalized and optimized for the iPhone SE and Gameboy Advance SP. All objects, such as buttons, text boxes, and the battle screen, should be scaled and positioned appropriately for these devices. The design should also include a Gameboy Advance SP frame around the battle screen to increase visual appeal and immerse the player in the game.
​

## Acceptance Criteria

- [x] The mobile-first design should be comp
- [x] All objects should be optimized for the iPhone SE 
- [x] The design should include a Gameboy Advance SP frame around the battle screen.
      ​

## Tasks

- [x] Finalize the mobile-first design by adjusting the CSS.
- [x] Scale and position all objects appropriately for the iPhone SE
- [x] Create a Gameboy Advance SP frame that surrounds the battle screen.
- [x] Make sure the design is optimized for the best user experience on these devices.
- [x] create the appropriate frame of the gameboy in Photoshop

**Comment by alinawinter** [comment]
Looks good :-D
