### ISSUE TITLE
Implement interactive text box for combat commands and attack feedback and revise UI

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project-pokemon-battler#24]
## Value Proposition

As a player
I would like to have an interactive text field that displays the name of my Pokemon and shows the attack it performs
to have a clear and dynamic combat experience.
​

## Description

![us11-1](https://user-images.githubusercontent.com/100302405/232451992-cce610c3-c13c-4c8a-98a6-aa0a42b72f6b.png)
![us11-2](https://user-images.githubusercontent.com/100302405/232451981-b4e9fd1b-554c-4965-97ba-500dfbf3a554.png)

p.s.: i see the spelling mistake in the wireframe too ... :D 
should of course be called "Feuersturm"

To enhance the user experience, the button layout on the battle screen needs to be redesigned. The buttons should be more intuitive and easier to navigate, making it simpler for players to select their commands. An interactive text box should be added to the battle screen. The player should be able to select a command by clicking on it. When the player selects an attack command, the text box should indicate which attack is being performed.
​

## Acceptance Criteria

- [x] An interactive textbox should be added to the battle screen.
- [x] Redesign the button layout to make it more intuitive and easier to navigate.
- [x] Button should be revised to be colored depending on the type of attack being displayed
- [x] The textbox should show which attack is being executed when the Attack command is selected.

## Tasks

- [x] Create an interactive textbox component for the combat screen.
- [x] Implement logic that indicates which attack will be performed when the Attack command is selected.
- [x] Redesign the button layout on the battle screen.
- [x] - Create new `AttackMessage.js` component.

**Comment by alinawinter** [comment]
Looks awesome! Maybe you can additionally describe in your AC when exactly the white field disappears
