### ISSUE TITLE
Implementing Interactive Textbox for Battle Commands and Attack Feedback

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project-pokemon-battler#28]
## Value Proposition

As a player
I would like to have an interactive text field that will display the battle command of the opponent Pokemon
to have a clear and dynamic combat experience.
​
## Description

![us13-1](https://user-images.githubusercontent.com/100302405/232779217-829bea2a-7cdc-48d9-86e5-6c60357fb997.png)
![us13-2](https://user-images.githubusercontent.com/100302405/232779205-74432627-d334-4a93-8fca-d9c57180d225.png)
​
## Acceptance Criteria

- [x] The interactive text field, after the attack of my Pokemon, should display the attack of the opponent Pokemon.
- [x] the textbox should only be visible for the duration of the attacks, then the selection menu should appear again 

## Tasks

- [x] To the already created interactive text field add the logic that the opponent attack is displayed.
- [x] adjust the useBattleLogic so that also the opponent attacks and the opponent Pokemon are passed to AttackMessage.js
