### ISSUE TITLE
Implementing the Attack Functionality and Winning Condition

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project-pokemon-battler#3]
## Value Proposition

- As a player
- I want to be able to attack the opponent's Pokemon
- in order to defeat them and feel accomplished.

## Description

![us2](https://user-images.githubusercontent.com/100302405/227528561-dcae3059-a3a8-4a15-a1e9-d8f22335db9a.png)

After the battle screen is displayed, the player should be prompted with the question "Klicke auf "Kampf" um anzugreifen" and presented with a button labeled "Kampf". When the player selects the "Kampf" button, a fixed amount of the opponent's HP should be deducted, based on the strength of the player's Pokemon attack. If the opponent's HP reaches zero, the battle is won and the player should be presented with a message "Du hast den Kampf gewonnen" and given the option to return to the previous menu.

## Acceptance criteria

- [x] The player should be prompted with the question "Klicke auf "Kampf" um anzugreifen" and presented with a button labeled "Kampf".
- [x] When the player selects the "Attack" button, a fixed amount of the opponent's HP should be deducted based on the strength of the player's Pokemon attack.
- [x] If the opponent's HP reaches zero, the player should be presented with a message "Du hast den Kampf gewonnen."

## Tasks

- [x] Add the "Klicke auf "Kampf" um anzugreifen" prompt and the "Kampf" button to the battle screen.
- [x] Implement the attack functionality based on the strength of the player's Pokemon attack.
- [x] Deduct the fixed amount of opponent's HP when the player attacks.
- [x]  If the opponent's HP reaches zero, display a message "Du hast den Kampf gewonnen." and give the option to return to the previous menu.
- [x] Write tests to ensure the functionality is working as intended.
- [x] Update the battle screen to display changes in opponent's HP after being attacked.

**Comment by liebeckm** [comment]
nice! 🤝

just small hints:

- It is better to write the exact text displayed in the wireframe into your criteria as well. So for example,  instead of "what do you want to do?", write "Was willst du tun?" into the acceptance criteria.

- also, I would center the "kampf" text into the button so it is more clear that this is a button.

**Comment by dennisbuchwald** [comment]
Thanks @liebeckm for looking at it! ❤️

I have changed. 😊
That the "fight" is displayed there so, is necessary for the following user stories. Besides, it is so faithful to the original, but I want to show the other minus points as soon as their function is integrated. 

Here you have a small preview of how it should look at the end:
![Bildschirm­foto 2023-03-24 um 11 55 00](https://user-images.githubusercontent.com/100302405/227502861-4c2db2ee-090d-4800-a294-b5a7d6684106.png)

**Comment by Efendi5** [comment]
Nice work man !
I want to play your game after finishing

**Comment by PReichetanz** [comment]
Hi Dennis,

a really good start for your user story! 🎉

💬 Let's discuss some issues which came to my mind while reading:

## Acceptance Criteria
- The question "Was willst Du tun?" is still irritating if I can only choose one option. Maybe move it to a later story when you add more options.
- What happens if you defeat the enemy (according to your value proposition, this should be possible)? How is the user informed about this? There should be a scribble / explanation how this will look like.

**Comment by dennisbuchwald** [comment]
Thanks @PReichetanz,  I hadn't thought of that, I revised the story and defined the end of the fight.

**Comment by liebeckm** [comment]
Great, nothing to add 💯!
