### ISSUE TITLE
Implementing Restart Button to Return to Menu Screen

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project-pokemon-battler#30]
## Value Proposition

As a player
I would like the restart button to return to the menu screen instead of restarting the entire game
so I can just return to the menu screen and start a new battle. 
​
## Description

![us14](https://user-images.githubusercontent.com/100302405/232815271-3f95ca26-bf0d-42db-b738-10fcc689b3f7.png)

![us14-2](https://user-images.githubusercontent.com/100302405/232814260-98b71efc-d54e-47b6-846c-81cf82aecacf.png)

The "Neustart" button should be updated to return the player to the menu screen instead of restarting the entire game. This allows the player to adjust their gameplay or start a new game without having to reload the entire game. The same functionality should apply to the "Flucht" button during combat, allowing the player to return to the menu screen when they want to retreat.
​
## Acceptance Criteria

- [ ] The Restart button should return the player to the menu screen.
- [ ] The "Flucht" button during battle should also return the player to the menu screen.

## Tasks

- [x] Update the restart button to return the player to the menu screen.
- [x] Implement logic to ensure that the Restart button returns the player to the Menu screen.
- [x] Update the "Flucht" button during combat to return the player to the menu screen.

**Comment by rabe200** [comment]
i am note sure from the description and without knowing the rest of your app which one is the restart button and where to find it, can you show it in the picture or describe it?

**Comment by dennisbuchwald** [comment]
hey @rabe200, thanks for looking, in the game there is either in the fight the option to leave the fight or after winning/losing a message appears with a "Neustart" button. This currently refreshes the page, this should be changed because the app should not be restarted, but only return to the selection menu. I hope it is clearer now I have also added another image. 

maybe you just try the app: [Pokemon Battler](https://capstone-project-pokemon-battler-app.vercel.app)

**Comment by XxKikoxX** [comment]
Fantastic app that will make you grow beyond yourself

**Comment by rabe200** [comment]
the second picture is very helpful, thank you!
