### ISSUE TITLE
Creating Unique Attack Animations for Certain Attacks

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project-pokemon-battler#31]
## Value Proposition

As a player
I want certain attacks to have unique animations during battle
in order to enhance the visual experience and make battles more engaging.

## Description

![us15](https://user-images.githubusercontent.com/100302405/232786107-28e196cc-663a-4b05-bc8e-364e36382099.png)

Unique attack animations should be added for certain attacks in the game. These animations should be visually appealing and should enhance the overall gameplay experience. The unique animations will provide a more immersive and engaging experience for the player

## Acceptance Criteria

- [ ] Unique attack animations should be added for certain attacks.
- [ ] The animations should be visually appealing and enhance the gameplay experience. ​
## Tasks

- [ ] Determine which attacks will have unique animations.
- [ ] Add a value that determines the animation to the array.
- [ ] Design and create unique attack animations for the identified attacks.
- [ ] Implement the unique attack animations in `useBattleLogic.js`

**Comment by Gblur** [comment]
Yeahh cool!!! 
LGTM
