### ISSUE TITLE
Implementing Enemy Attack Functionality and Losing Condition

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project-pokemon-battler#4]
## Value Proposition

- As a player
- I want to be able to be attacked by the opponent's Pokemon and lose the battle
- in order to experience a real battle and strategize my attacks.

## Description

![Image](https://user-images.githubusercontent.com/100302405/227558761-2654c10b-6c9b-4dcc-94f8-3faffea82018.png)

After the player attacks the opponent's Pokemon, the opponent's Pokemon should automatically attack back, deducting a fixed amount of the player's Pokemon HP. The player should not have input during the opponent's attack. If the player's Pokemon HP reaches zero, the battle is lost and the player should be presented with a message "Du hast den Kampf verloren." and given the option to return to the previous menu.

## Acceptance criteria

- [x]  After the player attacks the opponent's Pokemon, the opponent's Pokemon should automatically attack back and deduct a fixed amount of the player's Pokemon HP.
- [x] The player should not have input during the opponent's attack.
- [x] If the player's Pokemon HP reaches zero, the battle is lost and the player should be presented with a message "Du hast den Kampf verloren." and given the option to return to the previous menu.

## Tasks

- [x] Implement the enemy attack functionality and deduct a fixed amount of player's Pokemon HP.
- [x] Disable player input during the opponent's attack.
- [x] If the player's Pokemon HP reaches zero, display a message "Du hast den Kampf verloren."
- [x] Update the battle screen to display changes in player's Pokemon HP after being attacked.
- [x] Write tests to ensure the functionality is working as intended.

**Comment by Efendi5** [comment]
Was ist mit dem Text "Du hast gewonnen", falls der Kampf gewonnen wird?
Diese Option würde ich auch noch hinzufügen in diese User Story

**Comment by dennisbuchwald** [comment]
Die passiert schon in der der story davor. 😊
