### ISSUE TITLE
Implementing Attack Menu with Different Strengths

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project-pokemon-battler#8]
## Value Proposition

**As a player
**I want to be able to select different attacks with varying strengths
**in order to strategize my attacks and defeat the opponent's Pokemon.
​

## Description

![us3](https://user-images.githubusercontent.com/100302405/229488208-7f8d9a76-cded-4304-8583-edd726ad0293.png)

After the player selects the "Kampf" button, a menu with different attacks should be displayed. Each attack should have a different strength and be associated with a specific button. When the player selects an attack, the opponent's Pokemon should be deducted a fixed amount of HP, based on the strength of the attack.

## Acceptance Criteria

- [x] When the player selects the "Kampf" button, a menu with different attacks should be displayed.
- [x] Each attack should have a different strength and be associated with a specific button.
- [x] When the player selects an attack, the opponent's Pokemon should be deducted a fixed amount of HP, based on the strength of the attack.
      ​

## Tasks

- [x] Create an attack menu component to display different attacks.
- [x] Implement different attacks with varying strengths and associate them with specific buttons in the attack menu.
- [x] Deduct the opponent's Pokemon HP by the strength of the attack when the player selects an attack.
- [x] Update the battle screen to display changes in opponent's Pokemon HP after being attacked.

**Comment by alinawinter** [comment]
Looks super thought through and clear to me :-) will you decide by yourself, how "strong" an attack is and create a db.js with an array or so for that? Or will you catch the attacks with an API? (but probably that would be another user story if you want to do that :-D ) maybe you can mention that here, how you want to do that

**Comment by dennisbuchwald** [comment]
@alinawinter no i will specify values myself which will then be executed in a range of +/- 10.
i orient myself to the original attack strengths in the game. :-)
