### ISSUE TITLE
Implementing Switching Opponent's Pokemon and Battle Continuation

### ISSUE THREAD

**Issue by dennisbuchwald** [dennisbuchwald/capstone-project-pokemon-battler#9]
## Value Proposition

As a player
I want to face the second opponent's Pokemon after defeating the first one
in order to continue the battle and win the game.
​

## Description

![us5](https://user-images.githubusercontent.com/100302405/229497729-740500d4-343f-44fa-aa73-b286a022c391.png)

After the player defeats the first opponent's Pokemon, the second opponent's Pokemon should appear. The battle screen should be updated to display the new opponent's Pokemon, their name, and HP bar. The player should be able to continue the battle and strategize their attacks to defeat the new opponent's Pokemon.
​

## Acceptance Criteria

- [x] After the player defeats the first opponent's Pokemon, the second opponent's Pokemon should appear.
- [x] The battle screen should be updated to display the new opponent's Pokemon, their name, and HP bar.
- [x] The player should be able to continue the battle and strategize their attacks to defeat the new opponent's Pokemon.
      ​

## Tasks

- [x]  Implement logic to detect when the first opponent's Pokemon is defeated.
- [x] Update the battle screen to remove the defeated Pokemon and display the new opponent's Pokemon, their name, and HP bar.
- [x] Allow the player to continue the battle and strategize their attacks against the new opponent's Pokemon.

**Comment by alinawinter** [comment]
Super cool! I want to play this :-D * memories* maybe it would be helpful for you to be concrete already in the tasks of what exactly you'll do with regard to the code e.g. in which component you'll make changes or so (i always find this helpful for my own structuring but then often also the code changes and so being concrete is not always good/possible)
